spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/wiki}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}

spring.thymeleaf.cache=true
spring.h2.console.enabled=false
