spring.application.name=wiki

app.content.dir=${APP_CONTENT_DIR:/drive/wiki.temporyn.com}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB

app.admin.username=${ADMIN_USERNAME:admin}
app.admin.password-hash=${ADMIN_PASSWORD_HASH:$2y$10$69cTX9fDoWkT9q1drXwByOJ8vxH4x13hm.WwGUgMyrHJHov4/w7rK}
