spring.application.name=wiki

app.content.dir=${APP_CONTENT_DIR:/drive/wiki.temporyn.com}

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Session timeout: 8 hours.
server.servlet.session.timeout=8h