spring.web.resources.static-locations=file:src/main/resources/static/
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:src/main/resources/templates/

spring.devtools.restart.enabled=true

app.admin.username=${ADMIN_USERNAME:admin}
app.admin.password-hash=${ADMIN_PASSWORD_HASH:$2y$05$Ug5yb/Ep4A1NNhwbTkJA0e4UzQEzcuGqAO9J8ImgB9WcWc80TjKZm}
app.admin.totp-secret=${ADMIN_TOTP_SECRET:JBSWY3DPEHPK3PXP}
